### DISCUSSION TITLE
How to setup a "Reverse Proxy" for Docker installation.

### DISCUSSION THREAD

**Discussion by Applearcher80** [Part-DB/Part-DB-server#927] [Q&A] [answered]
My apologies I am not a Linux web guy at all.  I have my  PartDB Server on a Pi running Bookworm.  Are there any good instructions out there for setting up a reverse proxy for HTTPS access to use the camera and DigiKey connections? Preferably step by step.  Thanks in advance.

Edit Update:  I Didn't figure out the reverse proxy.  Added the Client_ID and Client_Secret to docker-compose.yaml and use the `sudo -E docker-compose -d up`  instead of clearing the cache as suggested.   Clicked OAuth and DigiKey started working.

**Comment by salfter** [comment, marked as answer]
I use [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy) with mine.  Setup is fairly simple once the hostname is provisioned...add this to your PartDB service in docker-compose.yml

```
    networks:
      - www
    labels:
      caddy: partdb.example.tld
      caddy.reverse_proxy: partdb.www:80
      caddy.log: partdb
      caddy.log.format: json
```

Note that the service is connected to an external network named "www," which is provisioned in the docker-compose file for caddy-docker-proxy.  You'll also need this in the PartDB docker-compose:

```
networks:
  www:
    name: www
    external: true
```
