### ISSUE TITLE
Octopart API

### ISSUE THREAD

**Issue by tbornon** [Part-DB/Part-DB-server#353]
**Describe the bug**
Hi,

I would like to configure the Octopart API. I followed the documentation https://docs.part-db.de/usage/information_provider_system.html but I can't get the Octopart provider to work. It is always displayed as disabled

**To Reproduce**

I'm running Part DB under docker. Here is my docker-compose.yml

```
version: '3.3'
services:
  partdb:
    container_name: partdb
    # By default Part-DB will be running under Port 8080, you can change it here
    ports:
      - '8080:80'
    volumes:
      # By default
      - ./uploads:/var/www/html/uploads
      - ./public_media:/var/www/html/public/media
      - ./db:/var/www/html/var/db
    restart: unless-stopped
    image: jbtronics/part-db1:v1.6.1
    depends_on:
      - database
    environment:
      # Replace SECRET_USER_PASSWORD with the value of MYSQL_PASSWORD from below
      - DATABASE_URL=mysql://partdb:REDACTED@partdb_database:3306/partdb
      # In docker env logs will be redirected to stderr
      - APP_ENV=docker
      - PROVIDER_OCTOPART_CLIENT_ID=REDACTED (got it from Nexar)
      - PROVIDER_OCTOPART_CLIENT_SECRET=REDACTED (got it from Nexar)
      # - PROVIDER_OCTOPART_CURRENCY=EUR
      # - PROVIDER_OCOTPART_COUNTRY=FR
      # - PROVIDER_OCTOPART_ONLY_AUTHORIZED_SELLERS=true
      # You can configure Part-DB using environment variables
      # Below you can find the most essential ones predefined
      # However you can add add any other environment configuration you want here
      # See .env file for all available options or https://docs.part-db.de/configuration.html

      # The language to use serverwide as default (en, de, ru, etc.)
      - DEFAULT_LANG=en
      # The default timezone to use serverwide (e.g. Europe/Berlin)
      - DEFAULT_TIMEZONE=Europe/Paris
      # The currency that is used inside the DB (and is assumed when no currency is set). This can not be changed later, so be sure to set it the currency used in your country
      - BASE_CURRENCY=EUR
      # The name of this installation. This will be shown as title in the browser and in the header of the website
      - INSTANCE_NAME=Part-DB

      # Allow users to download attachments to the server by providing an URL
      # This could be a potential security issue, as the user can retrieve any file the server has access to (via internet)
      - ALLOW_ATTACHMENT_DOWNLOADS=0
      # Use gravatars for user avatars, when user has no own avatar defined
      - USE_GRAVATAR=0

      # Override value if you want to show to show a given text on homepage.
      # When this is empty the content of config/banner.md is used as banner
      #- BANNER=This is a test banner<br>with a line break

  database:
    container_name: partdb_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # Change this Password
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_DATABASE: partdb
      MYSQL_USER: partdb
      MYSQL_PASSWORD: REDACTED
    # Uncomment the following line if you need to access, your MySQL database from outside of docker (e.g. for debugging), normally you should leave that disabled
    #ports:
    #  - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
```

**Server Side**
- Part-DB Version: v1.6.1
