### ISSUE TITLE
500: server internal error when hosted in subpath

### ISSUE THREAD

**Issue by lBombo** [Part-DB/Part-DB-server#462]
Hi, I have a problem trying to host the site in a sub path. I've followed all the tutorials I found on the internet and also checked through the issues here, but I can't come up with any.

This is my docker-compose.yml
```
name: dockercompose
version: "3.8"
services:
  partdb:
    container_name: partdb
    ports:
      - '5000:80'
    volumes:
      - ./volumes/partdb/uploads:/var/www/html/uploads
      - ./volumes/partdb/public_media:/var/www/html/public/media
      - ./volumes/partdb/db:/var/www/html/var/db
    restart: unless-stopped
    image: jbtronics/part-db1:latest
    environment:
      - DEFAULT_URI=sub.example.it/magazzino/
      - TRUSTED_PROXIES=172.0.0.0/31
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/db/app.db
      - APP_ENV=docker
      - DEFAULT_LANG=it
      - DEFAULT_TIMEZONE=Europe/Rome
      - BASE_CURRENCY=EUR
      - INSTANCE_NAME=Example
      - ALLOW_ATTACHMENT_DOWNLOADS=0
      - USE_GRAVATAR=1
      - BANNER=Example
```
And this is my nginx configuration file config.conf:
```
server {
    listen		80;
    server_name		sub.example.it;

    location /magazzino/ {
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Prefix "/magazzino";
	proxy_pass	http://partdb:80/;
    }
}
```
And this is the server error
![image](https://github.com/Part-DB/Part-DB-server/assets/143873266/a0379763-1d4f-43d2-904c-8008e6da6e85)

I also checked on the docker logs but I don't know what can be caused by.
![image](https://github.com/Part-DB/Part-DB-server/assets/143873266/ccd7c325-85e8-4a16-9c65-9b0b64411162)
