### ISSUE TITLE
500 Internal Server Error The XML file "../config/dbal.xml" is not valid

### ISSUE THREAD

**Issue by Pytonballoon810** [Part-DB/Part-DB-server#822]
**Describe the bug**
I was trying to set up backups and ran into this issue. I am running the PartDB via Portainer docker-compose and had no issues until now. I already stopped, deleted, restarted all the containers involved (SQL container and the app container). I also already deleted the container image for the app as the issue does not seem to be related to the My-SQL container. 

**Screenshots**
![image](https://github.com/user-attachments/assets/b02248d0-9ca5-45b7-8d16-f70d043439c0)
![image](https://github.com/user-attachments/assets/b633626e-3d5a-47bd-b07f-c4dc5594cf3b)

**Versions**
I am using the newest versions of everything. I just pulled the latest docker image

**Docker Compose**
```yaml
version: '3.3'
services:
  partdb:
    container_name: partdb
    ports:
      - '8100:80'
    volumes:
      - /home/partdb/uploads:/var/www/html/uploads
      - /home/partdb/backups:/tmp
      - /home/partdb/public_media:/var/www/html/public/media
      - /home/partdb/db:/var/www/html/var/db
    restart: unless-stopped
    image: jbtronics/part-db1:latest
    depends_on:
      - database
    environment:
      # Replace SECRET_USER_PASSWORD with the value of MYSQL_PASSWORD from below
      - DATABASE_URL=mysql://partdb:@database:3306/partdb
      # In docker env logs will be redirected to stderr
      - APP_ENV=docker

      # You can configure Part-DB using environment variables
      # Below you can find the most essential ones predefined
      # However you can add add any other environment configuration you want here
      # See .env file for all available options or https://docs.part-db.de/configuration.html

      # The language to use serverwide as default (en, de, ru, etc.)
      - DEFAULT_LANG=en
      # The default timezone to use serverwide (e.g. Europe/Berlin)
      - DEFAULT_TIMEZONE=Europe/Berlin
      # - DEFAULT_URI= https://parts.nobble.it
      # The currency that is used inside the DB (and is assumed when no currency is set). This can not be changed later, so be sure to set it the currency used in your country
      - BASE_CURRENCY=EUR
      # The name of this installation. This will be shown as title in the browser and in the header of the website
      - INSTANCE_NAME=Part-DB

      # Allow users to download attachments to the server by providing an URL
      # This could be a potential security issue, as the user can retrieve any file the server has access to (via internet)
      - ALLOW_ATTACHMENT_DOWNLOADS=1
      # Use gravatars for user avatars, when user has no own avatar defined
      - USE_GRAVATAR=1
      - PROVIDER_LCSC_ENABLED=1

      # Override value if you want to show to show a given text on homepage.
      # When this is empty the content of config/banner.md is used as banner
      #- BANNER=This is a test banner<br>with a line break

      - TRUSTED_PROXIES=10.0.0.0/8
    networks: 
      - casa
      
  database:
    container_name: partdb_database
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    environment:
      # Change this Password
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    # Uncomment the following line if you need to access, your MySQL database from outside of docker (e.g. for debugging), normally you should leave that disabled
    #ports:
    #  - '4306:3306'
    volumes:
      - /home/partdb/mysql:/var/lib/mysql
    networks: 
      - casa
networks:
  casa:
    external: true

```
