### ISSUE TITLE
Status 500 "Error calling /en/." since 1.16.0

### ISSUE THREAD

**Issue by Kabelkrant** [Part-DB/Part-DB-server#871]
**Describe the bug**
Since upgrading to 1.16.0, almost every page displays an error 500. It states: 

_error (Status 500)
Error calling [/en/](https://stuff.home.kabelkrant.net/en/).
Try to reload the page or contact the administrator if this error persists._

**To Reproduce**
1. On Synology Docker, run jbtronics/part-db1 version 1.15.2
2. Upgrade docker image to 1.16.0
3. Run `php bin/console doctrine:migrations:migrate` as user www-data, type Yes, migation succesful
4. Visit part-db in the browser and login
5. Error pops up

The error message advises to run `php bin/console cache:clear` but this does not help.

**Screenshots**
https://postimg.cc/4YYQJtnW

**Server Side**
Host 10.0.20.2
- Synology DSM 7.2.2 docker 
- jbtronics/part-db1:latest (port mapping 8091:80, see docker-compose below)

Host 10.0.20.4
- Ubuntu
- NGINX reverse proxy listening to host https://stuff.home.kabelkrant.net, forwarding to http://10.0.20.2:8091
- 11.4.4-MariaDB-ubu2404 - mariadb.org binary distribution 

**Desktop:**
 - Windows 10, Firefox 135

**Additional context**
My docker-compose is:

```
version: '3.3'
services:
  partdb:
    container_name: partdb
    ports:
      - '8091:80'
    volumes:
      - /volume1/docker/partdb/uploads:/var/www/html/uploads
      - /volume1/docker/partdb/public_media:/var/www/html/public/media
      - /volume1/docker/partdb/db:/var/www/html/var/db
    restart: unless-stopped
    image: jbtronics/part-db1:latest
    environment:
      - DATABASE_URL=mysql://stuff:(password)@10.0.20.4:3306/stuff
      - APP_ENV=docker
      - DEFAULT_LANG=en
      - DEFAULT_TIMEZONE=Europe/Amsterdam
      - BASE_CURRENCY=EUR
      - INSTANCE_NAME=Kabelkrant Inventaris
      - ALLOW_ATTACHMENT_DOWNLOADS=0
      - USE_GRAVATAR=0
      - DEFAULT_URI=https://stuff.home.kabelkrant.net
      - TRUSTED_PROXIES=10.0.20.0/16
      - BANNER=Welkom!

```
